DROP TABLE IF EXISTS CUSTOMER CASCADE ;

CREATE TABLE CUSTOMER (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  C_NAME VARCHAR(250) NOT NULL,
  PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS TRANSACTIONS CASCADE;

CREATE TABLE TRANSACTIONS (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  T_AMOUNT DECIMAL(100,2) NOT NULL,
  T_DATE DATE (250) NOT NULL,
  DESCRIPTION VARCHAR(250) NOT NULL,
  CATEGORY VARCHAR(250) NOT NULL,
  VENDOR VARCHAR(250) NOT NULL,
  CUSTOMER_ID BIGINT NOT NULL,
  FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(ID),
  PRIMARY KEY (ID)
);
